### ISSUE TITLE
Install fails, can'æt find gstreamer-1.0.pc

### ISSUE THREAD

**Issue by muffeeee** [dturing/node-gstreamer-superficial#22]
When I attempt `npm install -g gstreamer-superficial`, I get this error:

```

> gstreamer-superficial@0.0.4 install /usr/lib/node_modules/gstreamer-superficial
> node-gyp rebuild

Package gstreamer-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gstreamer-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gstreamer-1.0' found
gyp: Call to 'pkg-config gstreamer-1.0 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.9.24-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/gstreamer-superficial
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gstreamer-superficial@0.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gstreamer-superficial@0.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-21T22_33_32_975Z-debug.log
```

I do have gstreamer-1.0 installed (I've even used it), but as the whole cluster of gstreamer packages on Debian seem to be a huge mess, I might be on the wrong package.

Do you have any installation instructions?

**Comment by dturing** [comment]
Hi @muffeeee,

on debian, packages don't include the header files needed for development. Try:
`# sudo apt-get install libgstreamer1.0-dev`

**Comment by deedos** [comment]
For me, using Ubuntu 19.04, only works after installing "libgstreamer-plugins-base1.0-dev" and with this command:

`sudo npm install -g gstreamer-superficial --unsafe-perm=true --allow-root`

Hope it helps others..
