### ISSUE TITLE
After upgrading to GStreamer 1.16.0 -> I get an undefined symbol error

### ISSUE THREAD

**Issue by petergerten** [dturing/node-gstreamer-superficial#31]
After the gstreamer upgrade my node app won't launch anymore and I get:
```
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /app/ctrl/node_modules/gstreamer-superficial/build/Release/gstreamer-superficial.node: undefined symbol: _ZN2v86Object11SetAccessorENS_5LocalINS_7ContextEEENS1_INS_4NameEEEPFvS5E
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/ctrl/ctrl.min.js:1:79)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

**Comment by petergerten** [comment]
It turned out that was an unrelated build problem.
